### ISSUE TITLE
补充一段win自动写入注册表

### ISSUE THREAD

**Issue by kaishiqi** [lyzz0612/cocos_desktop_webview#1]
win的 createWebView 方法中，加入一段

	// WriteWebBrowserRegKey
	do 
	{
		HKEY hk;
		LPCTSTR str = TEXT("Software\\Microsoft\\Internet Explorer\\Main\\FeatureControl\\FEATURE_BROWSER_EMULATION");
		if (RegOpenKeyEx(HKEY_CURRENT_USER, str, 0, KEY_ALL_ACCESS, &hk) != 0) {
			CCLOG("!! Can not open regedit !!");
		} else {
			DWORD dwValue = 11001;
			if (RegSetValueEx(hk, TEXT("你的执行程序名.exe"), NULL, REG_DWORD, (const BYTE*)&dwValue, sizeof(dwValue)) != 0) {
				CCLOG("!! regedit wirte fail. %s !!", str);
			}
			RegCloseKey(hk);
		}
	} while (0);

可以实现自动写入注册表的机制，已经亲自测试过，可行。

**Comment by lyzz0612** [comment]
感谢建议，已经加入到代码中。执行程序名也改为动态获取
